# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_iiwa_pb2 as grpc__iiwa__pb2


class iiwaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.askCartesianPosition = channel.unary_unary(
        '/iiwaService/askCartesianPosition',
        request_serializer=grpc__iiwa__pb2.python_request.SerializeToString,
        response_deserializer=grpc__iiwa__pb2.robot_cartesian_position_reply.FromString,
        )
    self.askJointPosition = channel.unary_unary(
        '/iiwaService/askJointPosition',
        request_serializer=grpc__iiwa__pb2.python_request.SerializeToString,
        response_deserializer=grpc__iiwa__pb2.robot_joint_position_reply.FromString,
        )
    self.move = channel.unary_unary(
        '/iiwaService/move',
        request_serializer=grpc__iiwa__pb2.python_cartesian_position_request.SerializeToString,
        response_deserializer=grpc__iiwa__pb2.robot_reply.FromString,
        )
    self.move_with_orientation = channel.unary_unary(
        '/iiwaService/move_with_orientation',
        request_serializer=grpc__iiwa__pb2.python_cartesian_pose_request.SerializeToString,
        response_deserializer=grpc__iiwa__pb2.robot_reply.FromString,
        )
    self.auto_down = channel.unary_unary(
        '/iiwaService/auto_down',
        request_serializer=grpc__iiwa__pb2.force_condition.SerializeToString,
        response_deserializer=grpc__iiwa__pb2.robot_reply.FromString,
        )
    self.hold_position = channel.unary_unary(
        '/iiwaService/hold_position',
        request_serializer=grpc__iiwa__pb2.python_cartesian_pose_request.SerializeToString,
        response_deserializer=grpc__iiwa__pb2.robot_reply.FromString,
        )


class iiwaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def askCartesianPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def askJointPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def move(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def move_with_orientation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def auto_down(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def hold_position(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_iiwaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'askCartesianPosition': grpc.unary_unary_rpc_method_handler(
          servicer.askCartesianPosition,
          request_deserializer=grpc__iiwa__pb2.python_request.FromString,
          response_serializer=grpc__iiwa__pb2.robot_cartesian_position_reply.SerializeToString,
      ),
      'askJointPosition': grpc.unary_unary_rpc_method_handler(
          servicer.askJointPosition,
          request_deserializer=grpc__iiwa__pb2.python_request.FromString,
          response_serializer=grpc__iiwa__pb2.robot_joint_position_reply.SerializeToString,
      ),
      'move': grpc.unary_unary_rpc_method_handler(
          servicer.move,
          request_deserializer=grpc__iiwa__pb2.python_cartesian_position_request.FromString,
          response_serializer=grpc__iiwa__pb2.robot_reply.SerializeToString,
      ),
      'move_with_orientation': grpc.unary_unary_rpc_method_handler(
          servicer.move_with_orientation,
          request_deserializer=grpc__iiwa__pb2.python_cartesian_pose_request.FromString,
          response_serializer=grpc__iiwa__pb2.robot_reply.SerializeToString,
      ),
      'auto_down': grpc.unary_unary_rpc_method_handler(
          servicer.auto_down,
          request_deserializer=grpc__iiwa__pb2.force_condition.FromString,
          response_serializer=grpc__iiwa__pb2.robot_reply.SerializeToString,
      ),
      'hold_position': grpc.unary_unary_rpc_method_handler(
          servicer.hold_position,
          request_deserializer=grpc__iiwa__pb2.python_cartesian_pose_request.FromString,
          response_serializer=grpc__iiwa__pb2.robot_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iiwaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
